version: "3.7"

services:
  frontend:
    restart: always
    command: "yarn run start --hmr-port 1236"
    build:
      context: "./frontend"
    volumes:
      - ./frontend/:/root/app/
    environment:
      - HMR=1236
    ports:
      - "1236:1236"
    networks:
      - gate-tier

  nginx:
    restart: always
    build:
      context: "./nginx"
    networks:
      - gate-tier
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx:/var/log/nginx/
    # command: /bin/bash -c "envsubst < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    ports:
      - "8005:80"
      - "8006:8080"
      # - "1236:1236"

networks:
  gate-tier:
